version: "3.7"

services:

  webapp:
    container_name: uploadprogress-example
    image: uploadprogress-example
    build:
      context: ./.docker
      args:
        php_version: 7.4
        uploadprogress_version: 1.1.2
    ports:
      - "8080:80"
    volumes:
      - "./.tmp:/tmp"
      - ".:/var/www/html"
